bot:
  name: Artemka_Space_Bot
  token: 6926830872:AAGqBKlx4kWh5SwPsTR4zJkzcBTQaYj2mhM #token#
  owner: 510828058

#db related settings
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/telegram_bot_repository
    username: postgres
    password: 4253
    driver-class-name: org.postgresql.Driver

